version: "3.9"
services:
  atlas:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app

  db:
    image: postgres:14.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
